// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: server/proto/server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion string        `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind       string        `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata   *TaskMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec       *TaskSpec     `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *TaskRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TaskRequest) GetMetadata() *TaskMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskRequest) GetSpec() *TaskSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type TaskMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TaskMetadata) Reset() {
	*x = TaskMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMetadata) ProtoMessage() {}

func (x *TaskMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMetadata.ProtoReflect.Descriptor instead.
func (*TaskMetadata) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *TaskMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TaskSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *TaskSpec) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	File     *TaskFile    `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Params   []*TaskParam `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	Commands []string     `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	Livelog  int64        `protobuf:"varint,5,opt,name=livelog,proto3" json:"livelog,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetFile() *TaskFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *Task) GetParams() []*TaskParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Task) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Task) GetLivelog() int64 {
	if x != nil {
		return x.Livelog
	}
	return 0
}

type TaskFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Gzip    bool   `protobuf:"varint,2,opt,name=gzip,proto3" json:"gzip,omitempty"`
}

func (x *TaskFile) Reset() {
	*x = TaskFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFile) ProtoMessage() {}

func (x *TaskFile) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFile.ProtoReflect.Descriptor instead.
func (*TaskFile) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *TaskFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TaskFile) GetGzip() bool {
	if x != nil {
		return x.Gzip
	}
	return false
}

type TaskParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TaskParam) Reset() {
	*x = TaskParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskParam) ProtoMessage() {}

func (x *TaskParam) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskParam.ProtoReflect.Descriptor instead.
func (*TaskParam) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *TaskParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskParam) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output *TaskOutput `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error  string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TaskReply) Reset() {
	*x = TaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReply) ProtoMessage() {}

func (x *TaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReply.ProtoReflect.Descriptor instead.
func (*TaskReply) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *TaskReply) GetOutput() *TaskOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TaskReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos     int64  `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Time    int64  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *TaskOutput) GetPos() int64 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *TaskOutput) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TaskOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GlanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion string          `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind       string          `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata   *GlanceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec       *GlanceSpec     `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *GlanceRequest) Reset() {
	*x = GlanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceRequest) ProtoMessage() {}

func (x *GlanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceRequest.ProtoReflect.Descriptor instead.
func (*GlanceRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{8}
}

func (x *GlanceRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GlanceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GlanceRequest) GetMetadata() *GlanceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GlanceRequest) GetSpec() *GlanceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type GlanceMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GlanceMetadata) Reset() {
	*x = GlanceMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceMetadata) ProtoMessage() {}

func (x *GlanceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceMetadata.ProtoReflect.Descriptor instead.
func (*GlanceMetadata) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{9}
}

func (x *GlanceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GlanceSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Glance *Glance `protobuf:"bytes,1,opt,name=glance,proto3" json:"glance,omitempty"`
}

func (x *GlanceSpec) Reset() {
	*x = GlanceSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceSpec) ProtoMessage() {}

func (x *GlanceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceSpec.ProtoReflect.Descriptor instead.
func (*GlanceSpec) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{10}
}

func (x *GlanceSpec) GetGlance() *Glance {
	if x != nil {
		return x.Glance
	}
	return nil
}

type Glance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir  *GlanceDirReq  `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	File *GlanceFileReq `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Sys  *GlanceSysReq  `protobuf:"bytes,3,opt,name=sys,proto3" json:"sys,omitempty"`
}

func (x *Glance) Reset() {
	*x = Glance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Glance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Glance) ProtoMessage() {}

func (x *Glance) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Glance.ProtoReflect.Descriptor instead.
func (*Glance) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{11}
}

func (x *Glance) GetDir() *GlanceDirReq {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *Glance) GetFile() *GlanceFileReq {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *Glance) GetSys() *GlanceSysReq {
	if x != nil {
		return x.Sys
	}
	return nil
}

type GlanceDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GlanceDirReq) Reset() {
	*x = GlanceDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceDirReq) ProtoMessage() {}

func (x *GlanceDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceDirReq.ProtoReflect.Descriptor instead.
func (*GlanceDirReq) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{12}
}

func (x *GlanceDirReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GlanceFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxSize int64  `protobuf:"varint,1,opt,name=maxSize,proto3" json:"maxSize,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GlanceFileReq) Reset() {
	*x = GlanceFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceFileReq) ProtoMessage() {}

func (x *GlanceFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceFileReq.ProtoReflect.Descriptor instead.
func (*GlanceFileReq) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{13}
}

func (x *GlanceFileReq) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *GlanceFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GlanceSysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *GlanceSysReq) Reset() {
	*x = GlanceSysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceSysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceSysReq) ProtoMessage() {}

func (x *GlanceSysReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceSysReq.ProtoReflect.Descriptor instead.
func (*GlanceSysReq) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{14}
}

func (x *GlanceSysReq) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type GlanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir  *GlanceDirRep  `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	File *GlanceFileRep `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Sys  *GlanceSysRep  `protobuf:"bytes,3,opt,name=sys,proto3" json:"sys,omitempty"`
}

func (x *GlanceReply) Reset() {
	*x = GlanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceReply) ProtoMessage() {}

func (x *GlanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceReply.ProtoReflect.Descriptor instead.
func (*GlanceReply) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{15}
}

func (x *GlanceReply) GetDir() *GlanceDirRep {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *GlanceReply) GetFile() *GlanceFileRep {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *GlanceReply) GetSys() *GlanceSysRep {
	if x != nil {
		return x.Sys
	}
	return nil
}

type GlanceDirRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*GlanceEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *GlanceDirRep) Reset() {
	*x = GlanceDirRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceDirRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceDirRep) ProtoMessage() {}

func (x *GlanceDirRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceDirRep.ProtoReflect.Descriptor instead.
func (*GlanceDirRep) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{16}
}

func (x *GlanceDirRep) GetEntries() []*GlanceEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GlanceEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir bool   `protobuf:"varint,2,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Size  int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Time  string `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	User  string `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Group string `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	Mode  string `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *GlanceEntry) Reset() {
	*x = GlanceEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceEntry) ProtoMessage() {}

func (x *GlanceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceEntry.ProtoReflect.Descriptor instead.
func (*GlanceEntry) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{17}
}

func (x *GlanceEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GlanceEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *GlanceEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GlanceEntry) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *GlanceEntry) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GlanceEntry) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GlanceEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GlanceFileRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content  string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Readable bool   `protobuf:"varint,2,opt,name=readable,proto3" json:"readable,omitempty"`
}

func (x *GlanceFileRep) Reset() {
	*x = GlanceFileRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceFileRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceFileRep) ProtoMessage() {}

func (x *GlanceFileRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceFileRep.ProtoReflect.Descriptor instead.
func (*GlanceFileRep) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{18}
}

func (x *GlanceFileRep) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GlanceFileRep) GetReadable() bool {
	if x != nil {
		return x.Readable
	}
	return false
}

type GlanceSysRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *GlanceResource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Stats    *GlanceStats    `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *GlanceSysRep) Reset() {
	*x = GlanceSysRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceSysRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceSysRep) ProtoMessage() {}

func (x *GlanceSysRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceSysRep.ProtoReflect.Descriptor instead.
func (*GlanceSysRep) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{19}
}

func (x *GlanceSysRep) GetResource() *GlanceResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *GlanceSysRep) GetStats() *GlanceStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GlanceResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allocatable *GlanceAllocatable `protobuf:"bytes,1,opt,name=allocatable,proto3" json:"allocatable,omitempty"`
	Requested   *GlanceRequested   `protobuf:"bytes,2,opt,name=requested,proto3" json:"requested,omitempty"`
}

func (x *GlanceResource) Reset() {
	*x = GlanceResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceResource) ProtoMessage() {}

func (x *GlanceResource) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceResource.ProtoReflect.Descriptor instead.
func (*GlanceResource) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{20}
}

func (x *GlanceResource) GetAllocatable() *GlanceAllocatable {
	if x != nil {
		return x.Allocatable
	}
	return nil
}

func (x *GlanceResource) GetRequested() *GlanceRequested {
	if x != nil {
		return x.Requested
	}
	return nil
}

type GlanceAllocatable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MilliCPU int64 `protobuf:"varint,1,opt,name=milliCPU,proto3" json:"milliCPU,omitempty"`
	Memory   int64 `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage  int64 `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
}

func (x *GlanceAllocatable) Reset() {
	*x = GlanceAllocatable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceAllocatable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceAllocatable) ProtoMessage() {}

func (x *GlanceAllocatable) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceAllocatable.ProtoReflect.Descriptor instead.
func (*GlanceAllocatable) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{21}
}

func (x *GlanceAllocatable) GetMilliCPU() int64 {
	if x != nil {
		return x.MilliCPU
	}
	return 0
}

func (x *GlanceAllocatable) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *GlanceAllocatable) GetStorage() int64 {
	if x != nil {
		return x.Storage
	}
	return 0
}

type GlanceRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MilliCPU int64 `protobuf:"varint,1,opt,name=milliCPU,proto3" json:"milliCPU,omitempty"`
	Memory   int64 `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage  int64 `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
}

func (x *GlanceRequested) Reset() {
	*x = GlanceRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceRequested) ProtoMessage() {}

func (x *GlanceRequested) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceRequested.ProtoReflect.Descriptor instead.
func (*GlanceRequested) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{22}
}

func (x *GlanceRequested) GetMilliCPU() int64 {
	if x != nil {
		return x.MilliCPU
	}
	return 0
}

func (x *GlanceRequested) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *GlanceRequested) GetStorage() int64 {
	if x != nil {
		return x.Storage
	}
	return 0
}

type GlanceStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu     *GlanceCPU     `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ip      string         `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Memory  *GlanceMemory  `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Os      string         `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Storage *GlanceStorage `protobuf:"bytes,5,opt,name=storage,proto3" json:"storage,omitempty"`
}

func (x *GlanceStats) Reset() {
	*x = GlanceStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceStats) ProtoMessage() {}

func (x *GlanceStats) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceStats.ProtoReflect.Descriptor instead.
func (*GlanceStats) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{23}
}

func (x *GlanceStats) GetCpu() *GlanceCPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *GlanceStats) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GlanceStats) GetMemory() *GlanceMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *GlanceStats) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GlanceStats) GetStorage() *GlanceStorage {
	if x != nil {
		return x.Storage
	}
	return nil
}

type GlanceCPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total string `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	Used  string `protobuf:"bytes,2,opt,name=used,proto3" json:"used,omitempty"`
}

func (x *GlanceCPU) Reset() {
	*x = GlanceCPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceCPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceCPU) ProtoMessage() {}

func (x *GlanceCPU) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceCPU.ProtoReflect.Descriptor instead.
func (*GlanceCPU) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{24}
}

func (x *GlanceCPU) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *GlanceCPU) GetUsed() string {
	if x != nil {
		return x.Used
	}
	return ""
}

type GlanceMemory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total string `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	Used  string `protobuf:"bytes,2,opt,name=used,proto3" json:"used,omitempty"`
}

func (x *GlanceMemory) Reset() {
	*x = GlanceMemory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceMemory) ProtoMessage() {}

func (x *GlanceMemory) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceMemory.ProtoReflect.Descriptor instead.
func (*GlanceMemory) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{25}
}

func (x *GlanceMemory) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *GlanceMemory) GetUsed() string {
	if x != nil {
		return x.Used
	}
	return ""
}

type GlanceStorage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total string `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	Used  string `protobuf:"bytes,2,opt,name=used,proto3" json:"used,omitempty"`
}

func (x *GlanceStorage) Reset() {
	*x = GlanceStorage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_server_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlanceStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlanceStorage) ProtoMessage() {}

func (x *GlanceStorage) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_server_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlanceStorage.ProtoReflect.Descriptor instead.
func (*GlanceStorage) Descriptor() ([]byte, []int) {
	return file_server_proto_server_proto_rawDescGZIP(), []int{26}
}

func (x *GlanceStorage) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *GlanceStorage) GetUsed() string {
	if x != nil {
		return x.Used
	}
	return ""
}

var File_server_proto_server_proto protoreflect.FileDescriptor

var file_server_proto_server_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x75, 0x6e,
	0x6e, 0x65, 0x72, 0x22, 0x99, 0x01, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22,
	0x22, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x20, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73,
	0x6b, 0x22, 0xa1, 0x01, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x69, 0x76, 0x65, 0x6c, 0x6f, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x69,
	0x76, 0x65, 0x6c, 0x6f, 0x67, 0x22, 0x38, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x7a, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x67, 0x7a, 0x69, 0x70, 0x22,
	0x35, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4d, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4c, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x0d, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x32, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x0a, 0x47,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x26, 0x0a, 0x06, 0x67, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x06, 0x67, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x22, 0x83, 0x01, 0x0a, 0x06, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x03,
	0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x52,
	0x03, 0x64, 0x69, 0x72, 0x12, 0x29, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x26, 0x0a, 0x03, 0x73, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x79, 0x73, 0x52,
	0x65, 0x71, 0x52, 0x03, 0x73, 0x79, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x47, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x3d, 0x0a, 0x0d, 0x47,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x61, 0x78, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d,
	0x61, 0x78, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x26, 0x0a, 0x0c, 0x47, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x53, 0x79, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x0b, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x26, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44,
	0x69, 0x72, 0x52, 0x65, 0x70, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x29, 0x0a, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65,
	0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x73, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x53, 0x79, 0x73, 0x52, 0x65, 0x70, 0x52, 0x03, 0x73, 0x79, 0x73, 0x22, 0x3d, 0x0a,
	0x0c, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x70, 0x12, 0x2d, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x9d, 0x01, 0x0a,
	0x0b, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x45, 0x0a, 0x0d,
	0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x61,
	0x62, 0x6c, 0x65, 0x22, 0x6d, 0x0a, 0x0c, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x79, 0x73,
	0x52, 0x65, 0x70, 0x12, 0x32, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e,
	0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x75, 0x6e,
	0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22, 0x61, 0x0a, 0x11, 0x47, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x43, 0x50, 0x55, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x43, 0x50, 0x55, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x5f, 0x0a, 0x0f,
	0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x43, 0x50, 0x55, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x43, 0x50, 0x55, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0xb1, 0x01,
	0x0a, 0x0b, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x23, 0x0a,
	0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x75, 0x6e,
	0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x50, 0x55, 0x52, 0x03, 0x63,
	0x70, 0x75, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x70, 0x12, 0x2c, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73,
	0x12, 0x2f, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x22, 0x35, 0x0a, 0x09, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x50, 0x55, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x22, 0x38, 0x0a, 0x0c, 0x47, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x64, 0x22, 0x39, 0x0a, 0x0d, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x32, 0x87, 0x01,
	0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x38, 0x0a,
	0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x13, 0x2e, 0x72, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x47,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x67, 0x6f, 0x2f, 0x72, 0x75, 0x6e,
	0x6e, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_server_proto_server_proto_rawDescOnce sync.Once
	file_server_proto_server_proto_rawDescData = file_server_proto_server_proto_rawDesc
)

func file_server_proto_server_proto_rawDescGZIP() []byte {
	file_server_proto_server_proto_rawDescOnce.Do(func() {
		file_server_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_server_proto_rawDescData)
	})
	return file_server_proto_server_proto_rawDescData
}

var file_server_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_server_proto_server_proto_goTypes = []interface{}{
	(*TaskRequest)(nil),       // 0: runner.TaskRequest
	(*TaskMetadata)(nil),      // 1: runner.TaskMetadata
	(*TaskSpec)(nil),          // 2: runner.TaskSpec
	(*Task)(nil),              // 3: runner.Task
	(*TaskFile)(nil),          // 4: runner.TaskFile
	(*TaskParam)(nil),         // 5: runner.TaskParam
	(*TaskReply)(nil),         // 6: runner.TaskReply
	(*TaskOutput)(nil),        // 7: runner.TaskOutput
	(*GlanceRequest)(nil),     // 8: runner.GlanceRequest
	(*GlanceMetadata)(nil),    // 9: runner.GlanceMetadata
	(*GlanceSpec)(nil),        // 10: runner.GlanceSpec
	(*Glance)(nil),            // 11: runner.Glance
	(*GlanceDirReq)(nil),      // 12: runner.GlanceDirReq
	(*GlanceFileReq)(nil),     // 13: runner.GlanceFileReq
	(*GlanceSysReq)(nil),      // 14: runner.GlanceSysReq
	(*GlanceReply)(nil),       // 15: runner.GlanceReply
	(*GlanceDirRep)(nil),      // 16: runner.GlanceDirRep
	(*GlanceEntry)(nil),       // 17: runner.GlanceEntry
	(*GlanceFileRep)(nil),     // 18: runner.GlanceFileRep
	(*GlanceSysRep)(nil),      // 19: runner.GlanceSysRep
	(*GlanceResource)(nil),    // 20: runner.GlanceResource
	(*GlanceAllocatable)(nil), // 21: runner.GlanceAllocatable
	(*GlanceRequested)(nil),   // 22: runner.GlanceRequested
	(*GlanceStats)(nil),       // 23: runner.GlanceStats
	(*GlanceCPU)(nil),         // 24: runner.GlanceCPU
	(*GlanceMemory)(nil),      // 25: runner.GlanceMemory
	(*GlanceStorage)(nil),     // 26: runner.GlanceStorage
}
var file_server_proto_server_proto_depIdxs = []int32{
	1,  // 0: runner.TaskRequest.metadata:type_name -> runner.TaskMetadata
	2,  // 1: runner.TaskRequest.spec:type_name -> runner.TaskSpec
	3,  // 2: runner.TaskSpec.task:type_name -> runner.Task
	4,  // 3: runner.Task.file:type_name -> runner.TaskFile
	5,  // 4: runner.Task.params:type_name -> runner.TaskParam
	7,  // 5: runner.TaskReply.output:type_name -> runner.TaskOutput
	9,  // 6: runner.GlanceRequest.metadata:type_name -> runner.GlanceMetadata
	10, // 7: runner.GlanceRequest.spec:type_name -> runner.GlanceSpec
	11, // 8: runner.GlanceSpec.glance:type_name -> runner.Glance
	12, // 9: runner.Glance.dir:type_name -> runner.GlanceDirReq
	13, // 10: runner.Glance.file:type_name -> runner.GlanceFileReq
	14, // 11: runner.Glance.sys:type_name -> runner.GlanceSysReq
	16, // 12: runner.GlanceReply.dir:type_name -> runner.GlanceDirRep
	18, // 13: runner.GlanceReply.file:type_name -> runner.GlanceFileRep
	19, // 14: runner.GlanceReply.sys:type_name -> runner.GlanceSysRep
	17, // 15: runner.GlanceDirRep.entries:type_name -> runner.GlanceEntry
	20, // 16: runner.GlanceSysRep.resource:type_name -> runner.GlanceResource
	23, // 17: runner.GlanceSysRep.stats:type_name -> runner.GlanceStats
	21, // 18: runner.GlanceResource.allocatable:type_name -> runner.GlanceAllocatable
	22, // 19: runner.GlanceResource.requested:type_name -> runner.GlanceRequested
	24, // 20: runner.GlanceStats.cpu:type_name -> runner.GlanceCPU
	25, // 21: runner.GlanceStats.memory:type_name -> runner.GlanceMemory
	26, // 22: runner.GlanceStats.storage:type_name -> runner.GlanceStorage
	0,  // 23: runner.ServerProto.SendTask:input_type -> runner.TaskRequest
	8,  // 24: runner.ServerProto.SendGlance:input_type -> runner.GlanceRequest
	6,  // 25: runner.ServerProto.SendTask:output_type -> runner.TaskReply
	15, // 26: runner.ServerProto.SendGlance:output_type -> runner.GlanceReply
	25, // [25:27] is the sub-list for method output_type
	23, // [23:25] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_server_proto_server_proto_init() }
func file_server_proto_server_proto_init() {
	if File_server_proto_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_proto_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Glance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceSysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceDirRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceFileRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceSysRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceAllocatable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceCPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceMemory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_server_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlanceStorage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_server_proto_goTypes,
		DependencyIndexes: file_server_proto_server_proto_depIdxs,
		MessageInfos:      file_server_proto_server_proto_msgTypes,
	}.Build()
	File_server_proto_server_proto = out.File
	file_server_proto_server_proto_rawDesc = nil
	file_server_proto_server_proto_goTypes = nil
	file_server_proto_server_proto_depIdxs = nil
}
